drop database RPG_Backpack;
drop user rpgbackpack;
create user rpgbackpack with password 'Qwerty1!'
connect RPG_Backpack;
alter default privileges grant all on tables to RPG_Backpack;
alter default privileges grant all on sequences to RPG_Backpack;

CREATE EXTENSION pgcrypto

CREATE TABLE USERS (
  USR_ID SERIAL PRIMARY KEY,
  USR_LOGIN VARCHAR(40) NOT NULL UNIQUE,
  USR_NAME VARCHAR(25) NOT NULL,
  USR_PASSWORD VARCHAR(300) NOT NULL,
  USR_SUBSCRIPTION BOOLEAN DEFAULT false,
  USR_AUDIT_CREATED TIMESTAMP DEFAULT NOW(),
  USR_AUDIT_MODIFIED TIMESTAMP,
  USR_AUDIT_REMOVED TIMESTAMP,
  USR_AUDIT_SUBSCRIBED TIMESTAMP,
  USR_ADMIN BOOLEAN DEFAULT false,
  USR_PROFILE_IMAGE VARCHAR(100)
);

CREATE TABLE USER_SESSIONS (
  USS_ID SERIAL PRIMARY KEY,
  USS_USR_ID INTEGER,
  USS_SES_ID INTEGER,
  USS_GAME_MASTER BOOLEAN DEFAULT false,
  USS_AUDIT_JOINED TIMESTAMP DEFAULT NOW(),
  USS_AUDIT_LEFT TIMESTAMP
);

CREATE TABLE SESSIONS (
  SES_ID SERIAL PRIMARY KEY,
  SES_NAME VARCHAR(50) NOT NULL,
  SES_PASSWORD VARCHAR(300) NOT NULL,
  SES_MAX_ATTRIBUTES INTEGER DEFAULT 5,
  SES_AUDIT_CREATED TIMESTAMP DEFAULT NOW(),
  SES_AUDIT_MODIFIED TIMESTAMP,
  SES_AUDIT_REMOVED TIMESTAMP,
  SES_IMAGE VARCHAR(100)
);

CREATE TABLE SESSION_ATTRIBUTES (
  SEA_ID SERIAL PRIMARY KEY,
  SEA_SES_ID INTEGER,
  SEA_ATT_ID INTEGER,
  SEA_NAME VARCHAR(50),
  SEA_CATEGORY VARCHAR(50),
  SEA_REMOVABLE BOOLEAN DEFAULT true,
  SEA_AUDIT_CREATED TIMESTAMP DEFAULT NOW(),
  SEA_AUDIT_MODIFIED TIMESTAMP,
  SEA_AUDIT_REMOVED TIMESTAMP
);

CREATE TABLE ATTRIBUTE_TYPES (
  ATT_ID SERIAL PRIMARY KEY,
  ATT_NAME VARCHAR(50) UNIQUE
);

CREATE TABLE EQUIPMENT (
  EQU_ID SERIAL PRIMARY KEY,
  EQU_USS_ID INTEGER,
  EQU_NAME VARCHAR(50),
  EQU_MAX_SPACE FLOAT,
  EQU_MAX_WEIGHT FLOAT,
  EQU_PLAYER BOOLEAN DEFAULT true,
  EQU_PRIVATE BOOLEAN DEFAULT false,
  EQU_AUDIT_CREATED TIMESTAMP DEFAULT NOW(),
  EQU_AUDIT_MODIFIED TIMESTAMP,
  EQU_AUDIT_REMOVED TIMESTAMP
);

CREATE TABLE ITEMS (
  ITM_ID SERIAL PRIMARY KEY,
  ITM_EQU_ID INTEGER,
  ITM_NAME VARCHAR(50),
  ITM_AUDIT_CREATED TIMESTAMP DEFAULT NOW(),
  ITM_AUDIT_MODIFIED TIMESTAMP,
  ITM_AUDIT_REMOVED TIMESTAMP,
  ITM_IMAGE VARCHAR(100)
);

CREATE TABLE ITEMS_ATTRIBUTES_VALUE (
  ITA_ID SERIAL PRIMARY KEY,
  ITA_ITM_ID INTEGER,
  ITA_SEA_ID INTEGER,
  ITA_VALUE VARCHAR(200),
  ITA_AUDIT_MODIFIED TIMESTAMP
);

ALTER TABLE USER_SESSIONS ADD FOREIGN KEY (USS_USR_ID) REFERENCES USERS (USR_ID);

ALTER TABLE USER_SESSIONS ADD FOREIGN KEY (USS_SES_ID) REFERENCES SESSIONS (SES_ID);

ALTER TABLE SESSION_ATTRIBUTES ADD FOREIGN KEY (SEA_SES_ID) REFERENCES SESSIONS (SES_ID);

ALTER TABLE EQUIPMENT ADD FOREIGN KEY (EQU_USS_ID) REFERENCES USER_SESSIONS (USS_ID);

ALTER TABLE ITEMS ADD FOREIGN KEY (ITM_EQU_ID) REFERENCES EQUIPMENT (EQU_ID);

ALTER TABLE ITEMS_ATTRIBUTES_VALUE ADD FOREIGN KEY (ITA_ITM_ID) REFERENCES ITEMS (ITM_ID);

ALTER TABLE ITEMS_ATTRIBUTES_VALUE ADD FOREIGN KEY (ITA_SEA_ID) REFERENCES SESSION_ATTRIBUTES (SEA_ID);

ALTER TABLE SESSION_ATTRIBUTES ADD FOREIGN KEY (SEA_ATT_ID) REFERENCES ATTRIBUTE_TYPES (ATT_ID);

